import type { CreateUser } from "../../schema";

export const usersSeedData: CreateUser[] = [
  {
    id: crypto.randomUUID(),
    name: "John Doe",
    email: "john.doe@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Jane Smith",
    email: "jane.smith@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Michael Johnson",
    email: "michael.johnson@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: false,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Emily Davis",
    email: "emily.davis@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Robert Wilson",
    email: "robert.wilson@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Sarah Brown",
    email: "sarah.brown@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: false,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "David Miller",
    email: "david.miller@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Lisa Taylor",
    email: "lisa.taylor@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "James Anderson",
    email: "james.anderson@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Patricia Thomas",
    email: "patricia.thomas@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: false,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Daniel Jackson",
    email: "daniel.jackson@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Jennifer White",
    email: "jennifer.white@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Richard Martinez",
    email: "richard.martinez@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Susan Clark",
    email: "susan.clark@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: false,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Joseph Rodriguez",
    email: "joseph.rodriguez@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Nancy Lewis",
    email: "nancy.lewis@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Charles Lee",
    email: "charles.lee@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Margaret Walker",
    email: "margaret.walker@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: false,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Thomas Hall",
    email: "thomas.hall@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Karen Young",
    email: "karen.young@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Christopher Allen",
    email: "chris.allen@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: false,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Betty Scott",
    email: "betty.scott@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Edward King",
    email: "edward.king@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: true,
    image: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Wright",
    email: "laura.wright@example.com",
    createdAt: new Date(),
    updatedAt: new Date(),
    emailVerified: false,
    image: "",
  },
];
