/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as CommunitiesImport } from './routes/communities'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as UserUserIdImport } from './routes/user/$userId'
import { Route as CAllImport } from './routes/c/all'
import { Route as AuthenticatedSignOutImport } from './routes/_authenticated/sign-out'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as CNameIndexImport } from './routes/c/$name/index'
import { Route as UserUserIdPostsImport } from './routes/user/$userId/posts'
import { Route as UserUserIdOverviewImport } from './routes/user/$userId/overview'
import { Route as UserUserIdCommentsImport } from './routes/user/$userId/comments'
import { Route as CNameSettingsImport } from './routes/c/$name/settings'
import { Route as CNameIdImport } from './routes/c/$name/$id'
import { Route as AuthenticatedCNameCreateThreadImport } from './routes/_authenticated/c/$name/create-thread'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const CommunitiesRoute = CommunitiesImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserIdRoute = UserUserIdImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRoute,
} as any)

const CAllRoute = CAllImport.update({
  id: '/c/all',
  path: '/c/all',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSignOutRoute = AuthenticatedSignOutImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const CNameIndexRoute = CNameIndexImport.update({
  id: '/c/$name/',
  path: '/c/$name/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserIdPostsRoute = UserUserIdPostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => UserUserIdRoute,
} as any)

const UserUserIdOverviewRoute = UserUserIdOverviewImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => UserUserIdRoute,
} as any)

const UserUserIdCommentsRoute = UserUserIdCommentsImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => UserUserIdRoute,
} as any)

const CNameSettingsRoute = CNameSettingsImport.update({
  id: '/c/$name/settings',
  path: '/c/$name/settings',
  getParentRoute: () => rootRoute,
} as any)

const CNameIdRoute = CNameIdImport.update({
  id: '/c/$name/$id',
  path: '/c/$name/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedCNameCreateThreadRoute =
  AuthenticatedCNameCreateThreadImport.update({
    id: '/c/$name/create-thread',
    path: '/c/$name/create-thread',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/sign-out': {
      id: '/_authenticated/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthenticatedSignOutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/c/all': {
      id: '/c/all'
      path: '/c/all'
      fullPath: '/c/all'
      preLoaderRoute: typeof CAllImport
      parentRoute: typeof rootRoute
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdImport
      parentRoute: typeof rootRoute
    }
    '/c/$name/$id': {
      id: '/c/$name/$id'
      path: '/c/$name/$id'
      fullPath: '/c/$name/$id'
      preLoaderRoute: typeof CNameIdImport
      parentRoute: typeof rootRoute
    }
    '/c/$name/settings': {
      id: '/c/$name/settings'
      path: '/c/$name/settings'
      fullPath: '/c/$name/settings'
      preLoaderRoute: typeof CNameSettingsImport
      parentRoute: typeof rootRoute
    }
    '/user/$userId/comments': {
      id: '/user/$userId/comments'
      path: '/comments'
      fullPath: '/user/$userId/comments'
      preLoaderRoute: typeof UserUserIdCommentsImport
      parentRoute: typeof UserUserIdImport
    }
    '/user/$userId/overview': {
      id: '/user/$userId/overview'
      path: '/overview'
      fullPath: '/user/$userId/overview'
      preLoaderRoute: typeof UserUserIdOverviewImport
      parentRoute: typeof UserUserIdImport
    }
    '/user/$userId/posts': {
      id: '/user/$userId/posts'
      path: '/posts'
      fullPath: '/user/$userId/posts'
      preLoaderRoute: typeof UserUserIdPostsImport
      parentRoute: typeof UserUserIdImport
    }
    '/c/$name/': {
      id: '/c/$name/'
      path: '/c/$name'
      fullPath: '/c/$name'
      preLoaderRoute: typeof CNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/c/$name/create-thread': {
      id: '/_authenticated/c/$name/create-thread'
      path: '/c/$name/create-thread'
      fullPath: '/c/$name/create-thread'
      preLoaderRoute: typeof AuthenticatedCNameCreateThreadImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSignOutRoute: typeof AuthenticatedSignOutRoute
  AuthenticatedCNameCreateThreadRoute: typeof AuthenticatedCNameCreateThreadRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSignOutRoute: AuthenticatedSignOutRoute,
  AuthenticatedCNameCreateThreadRoute: AuthenticatedCNameCreateThreadRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UserUserIdRouteChildren {
  UserUserIdCommentsRoute: typeof UserUserIdCommentsRoute
  UserUserIdOverviewRoute: typeof UserUserIdOverviewRoute
  UserUserIdPostsRoute: typeof UserUserIdPostsRoute
}

const UserUserIdRouteChildren: UserUserIdRouteChildren = {
  UserUserIdCommentsRoute: UserUserIdCommentsRoute,
  UserUserIdOverviewRoute: UserUserIdOverviewRoute,
  UserUserIdPostsRoute: UserUserIdPostsRoute,
}

const UserUserIdRouteWithChildren = UserUserIdRoute._addFileChildren(
  UserUserIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/sign-in': typeof SignInRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sign-out': typeof AuthenticatedSignOutRoute
  '/c/all': typeof CAllRoute
  '/user/$userId': typeof UserUserIdRouteWithChildren
  '/c/$name/$id': typeof CNameIdRoute
  '/c/$name/settings': typeof CNameSettingsRoute
  '/user/$userId/comments': typeof UserUserIdCommentsRoute
  '/user/$userId/overview': typeof UserUserIdOverviewRoute
  '/user/$userId/posts': typeof UserUserIdPostsRoute
  '/c/$name': typeof CNameIndexRoute
  '/c/$name/create-thread': typeof AuthenticatedCNameCreateThreadRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/sign-in': typeof SignInRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sign-out': typeof AuthenticatedSignOutRoute
  '/c/all': typeof CAllRoute
  '/user/$userId': typeof UserUserIdRouteWithChildren
  '/c/$name/$id': typeof CNameIdRoute
  '/c/$name/settings': typeof CNameSettingsRoute
  '/user/$userId/comments': typeof UserUserIdCommentsRoute
  '/user/$userId/overview': typeof UserUserIdOverviewRoute
  '/user/$userId/posts': typeof UserUserIdPostsRoute
  '/c/$name': typeof CNameIndexRoute
  '/c/$name/create-thread': typeof AuthenticatedCNameCreateThreadRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/sign-in': typeof SignInRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sign-out': typeof AuthenticatedSignOutRoute
  '/c/all': typeof CAllRoute
  '/user/$userId': typeof UserUserIdRouteWithChildren
  '/c/$name/$id': typeof CNameIdRoute
  '/c/$name/settings': typeof CNameSettingsRoute
  '/user/$userId/comments': typeof UserUserIdCommentsRoute
  '/user/$userId/overview': typeof UserUserIdOverviewRoute
  '/user/$userId/posts': typeof UserUserIdPostsRoute
  '/c/$name/': typeof CNameIndexRoute
  '/_authenticated/c/$name/create-thread': typeof AuthenticatedCNameCreateThreadRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/communities'
    | '/sign-in'
    | '/profile'
    | '/sign-out'
    | '/c/all'
    | '/user/$userId'
    | '/c/$name/$id'
    | '/c/$name/settings'
    | '/user/$userId/comments'
    | '/user/$userId/overview'
    | '/user/$userId/posts'
    | '/c/$name'
    | '/c/$name/create-thread'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/communities'
    | '/sign-in'
    | '/profile'
    | '/sign-out'
    | '/c/all'
    | '/user/$userId'
    | '/c/$name/$id'
    | '/c/$name/settings'
    | '/user/$userId/comments'
    | '/user/$userId/overview'
    | '/user/$userId/posts'
    | '/c/$name'
    | '/c/$name/create-thread'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/communities'
    | '/sign-in'
    | '/_authenticated/profile'
    | '/_authenticated/sign-out'
    | '/c/all'
    | '/user/$userId'
    | '/c/$name/$id'
    | '/c/$name/settings'
    | '/user/$userId/comments'
    | '/user/$userId/overview'
    | '/user/$userId/posts'
    | '/c/$name/'
    | '/_authenticated/c/$name/create-thread'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRoute
  SignInRoute: typeof SignInRoute
  CAllRoute: typeof CAllRoute
  UserUserIdRoute: typeof UserUserIdRouteWithChildren
  CNameIdRoute: typeof CNameIdRoute
  CNameSettingsRoute: typeof CNameSettingsRoute
  CNameIndexRoute: typeof CNameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CommunitiesRoute: CommunitiesRoute,
  SignInRoute: SignInRoute,
  CAllRoute: CAllRoute,
  UserUserIdRoute: UserUserIdRouteWithChildren,
  CNameIdRoute: CNameIdRoute,
  CNameSettingsRoute: CNameSettingsRoute,
  CNameIndexRoute: CNameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/communities",
        "/sign-in",
        "/c/all",
        "/user/$userId",
        "/c/$name/$id",
        "/c/$name/settings",
        "/c/$name/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/profile",
        "/_authenticated/sign-out",
        "/_authenticated/c/$name/create-thread"
      ]
    },
    "/communities": {
      "filePath": "communities.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/sign-out": {
      "filePath": "_authenticated/sign-out.tsx",
      "parent": "/_authenticated"
    },
    "/c/all": {
      "filePath": "c/all.tsx"
    },
    "/user/$userId": {
      "filePath": "user/$userId.tsx",
      "children": [
        "/user/$userId/comments",
        "/user/$userId/overview",
        "/user/$userId/posts"
      ]
    },
    "/c/$name/$id": {
      "filePath": "c/$name/$id.tsx"
    },
    "/c/$name/settings": {
      "filePath": "c/$name/settings.tsx"
    },
    "/user/$userId/comments": {
      "filePath": "user/$userId/comments.tsx",
      "parent": "/user/$userId"
    },
    "/user/$userId/overview": {
      "filePath": "user/$userId/overview.tsx",
      "parent": "/user/$userId"
    },
    "/user/$userId/posts": {
      "filePath": "user/$userId/posts.tsx",
      "parent": "/user/$userId"
    },
    "/c/$name/": {
      "filePath": "c/$name/index.tsx"
    },
    "/_authenticated/c/$name/create-thread": {
      "filePath": "_authenticated/c/$name/create-thread.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
