/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThreadsImport } from './routes/threads'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as UserUsernameImport } from './routes/user/$username'
import { Route as CAllImport } from './routes/c/all'
import { Route as AuthenticatedSignOutImport } from './routes/_authenticated/sign-out'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedCreateThreadImport } from './routes/_authenticated/create-thread'
import { Route as CNameIndexImport } from './routes/c/$name/index'
import { Route as CNameIdImport } from './routes/c/$name/$id'
import { Route as AuthenticatedCNameCreateThreadImport } from './routes/_authenticated/c/$name/create-thread'

// Create/Update Routes

const ThreadsRoute = ThreadsImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUsernameRoute = UserUsernameImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRoute,
} as any)

const CAllRoute = CAllImport.update({
  id: '/c/all',
  path: '/c/all',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSignOutRoute = AuthenticatedSignOutImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateThreadRoute = AuthenticatedCreateThreadImport.update({
  id: '/create-thread',
  path: '/create-thread',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const CNameIndexRoute = CNameIndexImport.update({
  id: '/c/$name/',
  path: '/c/$name/',
  getParentRoute: () => rootRoute,
} as any)

const CNameIdRoute = CNameIdImport.update({
  id: '/c/$name/$id',
  path: '/c/$name/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedCNameCreateThreadRoute =
  AuthenticatedCNameCreateThreadImport.update({
    id: '/c/$name/create-thread',
    path: '/c/$name/create-thread',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/create-thread': {
      id: '/_authenticated/create-thread'
      path: '/create-thread'
      fullPath: '/create-thread'
      preLoaderRoute: typeof AuthenticatedCreateThreadImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/sign-out': {
      id: '/_authenticated/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthenticatedSignOutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/c/all': {
      id: '/c/all'
      path: '/c/all'
      fullPath: '/c/all'
      preLoaderRoute: typeof CAllImport
      parentRoute: typeof rootRoute
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameImport
      parentRoute: typeof rootRoute
    }
    '/c/$name/$id': {
      id: '/c/$name/$id'
      path: '/c/$name/$id'
      fullPath: '/c/$name/$id'
      preLoaderRoute: typeof CNameIdImport
      parentRoute: typeof rootRoute
    }
    '/c/$name/': {
      id: '/c/$name/'
      path: '/c/$name'
      fullPath: '/c/$name'
      preLoaderRoute: typeof CNameIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/c/$name/create-thread': {
      id: '/_authenticated/c/$name/create-thread'
      path: '/c/$name/create-thread'
      fullPath: '/c/$name/create-thread'
      preLoaderRoute: typeof AuthenticatedCNameCreateThreadImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedCreateThreadRoute: typeof AuthenticatedCreateThreadRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSignOutRoute: typeof AuthenticatedSignOutRoute
  AuthenticatedCNameCreateThreadRoute: typeof AuthenticatedCNameCreateThreadRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateThreadRoute: AuthenticatedCreateThreadRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSignOutRoute: AuthenticatedSignOutRoute,
  AuthenticatedCNameCreateThreadRoute: AuthenticatedCNameCreateThreadRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/threads': typeof ThreadsRoute
  '/create-thread': typeof AuthenticatedCreateThreadRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sign-out': typeof AuthenticatedSignOutRoute
  '/c/all': typeof CAllRoute
  '/user/$username': typeof UserUsernameRoute
  '/c/$name/$id': typeof CNameIdRoute
  '/c/$name': typeof CNameIndexRoute
  '/c/$name/create-thread': typeof AuthenticatedCNameCreateThreadRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/threads': typeof ThreadsRoute
  '/create-thread': typeof AuthenticatedCreateThreadRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sign-out': typeof AuthenticatedSignOutRoute
  '/c/all': typeof CAllRoute
  '/user/$username': typeof UserUsernameRoute
  '/c/$name/$id': typeof CNameIdRoute
  '/c/$name': typeof CNameIndexRoute
  '/c/$name/create-thread': typeof AuthenticatedCNameCreateThreadRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/threads': typeof ThreadsRoute
  '/_authenticated/create-thread': typeof AuthenticatedCreateThreadRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sign-out': typeof AuthenticatedSignOutRoute
  '/c/all': typeof CAllRoute
  '/user/$username': typeof UserUsernameRoute
  '/c/$name/$id': typeof CNameIdRoute
  '/c/$name/': typeof CNameIndexRoute
  '/_authenticated/c/$name/create-thread': typeof AuthenticatedCNameCreateThreadRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/sign-in'
    | '/threads'
    | '/create-thread'
    | '/profile'
    | '/sign-out'
    | '/c/all'
    | '/user/$username'
    | '/c/$name/$id'
    | '/c/$name'
    | '/c/$name/create-thread'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/sign-in'
    | '/threads'
    | '/create-thread'
    | '/profile'
    | '/sign-out'
    | '/c/all'
    | '/user/$username'
    | '/c/$name/$id'
    | '/c/$name'
    | '/c/$name/create-thread'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/threads'
    | '/_authenticated/create-thread'
    | '/_authenticated/profile'
    | '/_authenticated/sign-out'
    | '/c/all'
    | '/user/$username'
    | '/c/$name/$id'
    | '/c/$name/'
    | '/_authenticated/c/$name/create-thread'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  ThreadsRoute: typeof ThreadsRoute
  CAllRoute: typeof CAllRoute
  UserUsernameRoute: typeof UserUsernameRoute
  CNameIdRoute: typeof CNameIdRoute
  CNameIndexRoute: typeof CNameIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  ThreadsRoute: ThreadsRoute,
  CAllRoute: CAllRoute,
  UserUsernameRoute: UserUsernameRoute,
  CNameIdRoute: CNameIdRoute,
  CNameIndexRoute: CNameIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/sign-in",
        "/threads",
        "/c/all",
        "/user/$username",
        "/c/$name/$id",
        "/c/$name/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/create-thread",
        "/_authenticated/profile",
        "/_authenticated/sign-out",
        "/_authenticated/c/$name/create-thread"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/threads": {
      "filePath": "threads.tsx"
    },
    "/_authenticated/create-thread": {
      "filePath": "_authenticated/create-thread.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/sign-out": {
      "filePath": "_authenticated/sign-out.tsx",
      "parent": "/_authenticated"
    },
    "/c/all": {
      "filePath": "c/all.tsx"
    },
    "/user/$username": {
      "filePath": "user/$username.tsx"
    },
    "/c/$name/$id": {
      "filePath": "c/$name/$id.tsx"
    },
    "/c/$name/": {
      "filePath": "c/$name/index.tsx"
    },
    "/_authenticated/c/$name/create-thread": {
      "filePath": "_authenticated/c/$name/create-thread.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
